_BASE_: "./bases/Base-RCNN-FPN.yaml"
MODEL:
  # COCO ResNet50 weights
  WEIGHTS: "./output/lr0.001_aug/model_final.pth"
  MASK_ON: False # Not doing segmentation
  RESNETS:
    DEPTH: 50 # ResNet50
  ROI_HEADS:
    NUM_CLASSES: 1 # Change to suit own task
    # Can reduce this for lower memory/faster training; Default 512
    BATCH_SIZE_PER_IMAGE: 512
  BACKBONE:
    FREEZE_AT: 2 # Default 2
    NAME: "build_resnet_fpn_backbone_quantize"
DATASETS:
  TRAIN: ("login_train",)
  TEST: ("login_test",)
DATALOADER:
  NUM_WORKERS: 0
SOLVER:
  IMS_PER_BATCH: 8 # Batch size; Default 16
  BASE_LR: 0.001
  # (2/3, 8/9)
  STEPS: (12000, 16000) # The iteration number to decrease learning rate by GAMMA.
  MAX_ITER: 18000 # Number of training iterations
  CHECKPOINT_PERIOD: 4000 # Saves checkpoint every number of steps
INPUT:
  MIN_SIZE_TRAIN: (640, 672, 704, 736, 768, 800) # Image input sizes
TEST:
  # The period (in terms of steps) to evaluate the model during training.
  # Set to 0 to disable.
  EVAL_PERIOD: 2000
OUTPUT_DIR: "./output/lr0.001_finetune" # Specify output directory


