name: Setup tests
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  Linux_Docker_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t phishintention .

      - name: Run unit tests
        run: docker run --rm phishintention pixi run python -m unittest tests/test_all_steps.py

      - name: Run pipeline test
        run: docker run --rm phishintention pixi run python -m phishintention --folder datasets/test_sites --output_fn test_1228.json
